##   ____           _                ____
##  / ___|__ _  ___| |_ _   _ ___   / ___|__ _ _ __  _   _  ___  _ __
## | |   / _` |/ __| __| | | / __| | |   / _` | '_ \| | | |/ _ \| '_ \
## | |__| (_| | (__| |_| |_| \__ \ | |__| (_| | | | | |_| | (_) | | | |
##  \____\__,_|\___|\__|\__,_|___/  \____\__,_|_| |_|\__, |\___/|_| |_|
##                                                   |___/
##           ___ ___  _  _ _____ ___ _  _ _   _ ___ ___
##          / __/ _ \| \| |_   _|_ _| \| | | | | __|   \
##         | (_| (_) | .` | | |  | || .` | |_| | _|| |) |
##          \___\___/|_|\_| |_| |___|_|\_|\___/|___|___/
##
## A P-ROC Project by Eric Priepke, Copyright 2012
## Built on the PyProcGame Framework from Adam Preble and Gerry Stellenberg
## Original Cactus Canyon software by Matt Coriale
##

# P-ROC Game Description file for Bally Cactus Canyon
PRGame:
    machineType: wpc95
    numBalls: 4
PRFlippers:
    - flipperLwR
    - flipperLwL
PRBumpers:
    - leftSlingshot
    - rightSlingshot
    - leftJetBumper
    - rightJetBumper
    - bottomJetBumper
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #    'NC' (normally closed.  Common for optos)

    #Flipper Grounded Swithes
    ## EOS switches?
    flipperLwR:
        number: SF2
    flipperLwL:
        number: SF4

    #Dedicated Grounded Swtches
    exit: 
        number: SD5
    down: 
        number: SD6
    up: 
        number: SD7
    enter: 
        number: SD8

    #Regular Switches
    phantomSwitch2:
        number: S11
    startButton:
        number: S13
    plumbBobTilt:
        number: S14
    mineEntrance:
        number: S15
    leftOutlane:
        number: S16
    rightReturnLane:
        number: S17
    shooterLane:
        number: S18
    tilt:
        number: S21
    coinDoorClosed:
        number: S22
    alwaysClosed:
        number: S24
    leftReturnLane:
        number: S26
    rightOutlane:
        number: S27
    bottomRightStandUp:
        number: S28
    troughEject:
        number: S31
        type: 'NC'
    troughBallOne:
        number: S32
        type: 'NC'
    troughBallTwo:
        number: S33
        type: 'NC'
    troughBallThree:
        number: S34
        type: 'NC'
    troughBallFour:
        number: S35
        type: 'NC'
    leftLoopBottom:
        number: S36
        type: 'NC'
    rightLoopBottom:
        number: S37
        type: 'NC'
    minePopper:
        number: S41
        type: 'NC'
    saloonPopper:
        number: S42
        type: 'NC'
    phantomSwitch:
        number: S43
    topRightStandUp:
        number: S44
    beerMug:
        number: S46
    leftBonusLane:
        number: S47
    jetBumpersExit:
        number: S48
    leftSlingshot:
        number: S51
    rightSlingshot:
        number: S52
    leftJetBumper:
        number: S53
    rightJetBumper:
        number: S54
    bottomJetBumper:
        number: S55
    rightLoopTop:
        number: S56
    rightBonusLane:
        number: S57
    leftLoopTop:
        number: S58
    badGuySW0:
        number: S61
    badGuySW1:
        number: S62
    badGuySW2:
        number: S63
    badGuySW3:
        number: S64
    rightRampMake:
        number: S65
    rightRampEnter:
        number: S66
    skillBowl:
        number: S67
    rightRampBottom:
        number: S68
    trainEncoder:
        number: S71
    trainHome:
        number: S72
    saloonGate:
        number: S73
    saloonBart:
        number: S75
    mineHome:
        number: S77
        type: 'NC'
    mineEncoder:
        number: S78
        type: 'NC'
    centerRampEnter:
        number: S82
    leftRampMake:
        number: S83
    centerRampMake:
        number: S84
    leftRampEnter:
        number: S85
    topLeftStandUp:
        number: S86
    bottomLeftStandUp:
        number: S87
    
PRCoils:
    flipperLwRMain:
        number: FLRM
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
    flipperLwLHold:
        number: FLLH
    moveBart:
        number: FURM
    moveBartHat:
        number: FULH
    autoPlunger:
        number: C01
    badGuyC0:
        number: C02
    badGuyC1:
        number: C03
    badGuyC2:
        number: C04
    badGuyC3:
        number: C05
    minePopper:
        number: C06
    saloonPopper:
        number: C08
    troughEject:
        number: C09
    leftSlingshot:
        number: C10
    rightSlingshot:
        number: C11
    leftJetBumper:
        number: C12
    rightJetBumper:
        number: C13
    leftGunFightPost:
        number: C14
    rightGunFightPost:
        number: C15
    bottomJetBumper:
        number: C16
    mineMotor:
        number: C17
    mineFlasher:
        number: C18
    leftGunFlasher:
        number: C19
    rightGunFlasher:
        number: C20
    leftLoopGate:
        number: C21
    rightLoopGate:
        number: C22
    beaconFlasher:
        number: C24
    middleRightFlasher:
        number: C25
    saloonFlasher:
        number: C26
    backRightFlasher:
        number: C27
    backLeftFlasher:
        number: C28
    trainReverse:
        number: C37
    trainForward:
        number: C38

PRLamps:
    rankStranger:
        number: L11
        tags: Playfield
    rankPartner:
        number: L12
        tags: Playfield
    rankDeputy:
        number: L13
        tags: Playfield
    rankSheriff:
        number: L14
        tags: Playfield
    rankMarshall:
        number: L15
        tags: Playfield
    starMotherlode:
        number: L16
        tags: Playfield
    leftBonusLane:
        number: L17
        tags: Playfield
    rightBonusLane:
        number: L18
        tags: Playfield
    bountyBeacon:
        number: L21
        tags: Playfield
    jackpotBeacon:
        number: L22
        tags: Playfield
    shootToCollect:
        number: L23
        tags: Playfield
    extraBallLitBeacon:
        number: L24
        tags: Playfield
    bountySaloon:
        number: L25
        tags: Playfield
    saloonArrow:
        number: L26
        tags: Playfield
    extraBall:
        number: L27
        tags: Playfield
    mineLock:
        number: L28
        tags: Playfield
    badGuyL2:
        number: L31
        tags: Playfield
    badGuyL0:
        number: L32
        tags: Playfield
    leftQuickdraw:
        number: L33
        tags: Playfield
    rightRampSoundAlarm:
        number: L34
        tags: Playfield
    rightRampShootOut:
        number: L35
        tags: Playfield
    rightRampSavePolly:
        number: L36
        tags: Playfield
    rightRampJackpot:
        number: L37
        tags: Playfield
    rightRampCombo:
        number: L38
        tags: Playfield
    rightLoopCombo:
        number: L41
        tags: Playfield
    rightLoopJackpot:
        number: L42
        tags: Playfield
    rightLoopMarksman:
        number: L43
        tags: Playfield
    rightLoopGunslinger:
        number: L44
        tags: Playfield
    rightLoopGoodShot:
        number: L45
        tags: Playfield
    leftReturnQuickdraw:
        number: L46
        tags: Playfield
    leftGunfightPin:
        number: L47
        tags: Playfield
    leftOutGunfight:
        number: L48
        tags: Playfield
    badGuyL3:
        number: L51
        tags: Playfield
    bottomRightQuickdraw:
        number: L52
        tags: Playfield
    topRightQuickdraw:
        number: L53
        tags: Playfield
    centerRampCatchTrain:
        number: L54
        tags: Playfield
    centerRampStopTrain:
        number: L55
        tags: Playfield
    centerRampSavePolly:
        number: L56
        tags: Playfield
    centerRampJackpot:
        number: L57
        tags: Playfield
    centerRampCombo:
        number: L58
        tags: Playfield
    leftRampWhiteWater:
        number: L61
        tags: Playfield
    leftRampWaterfall:
        number: L62
        tags: Playfield
    leftRampSavePolly:
        number: L63
        tags: Playfield
    leftRampJackpot:
        number: L64
        tags: Playfield
    leftRampCombo:
        number: L65
        tags: Playfield
    rightReturnQuickdraw:
        number: L66
        tags: Playfield
    rightOutSpecial:
        number: L67
        tags: Playfield
    rightGunfightPin:
        number: L68
        tags: Playfield
    starStampede:
        number: L71
        tags: Playfield
    starCombo:
        number: L72
        tags: Playfield
    starHighNoon:
        number: L73
        tags: Playfield
    leftLoopCombo:
        number: L74
        tags: Playfield
    leftLoopJackpot:
        number: L75
        tags: Playfield
    leftLoopRideEm:
        number: L76
        tags: Playfield
    leftLoopWildRide:
        number: L77
        tags: Playfield
    leftLoopBuckNBronco:
        number: L78
        tags: Playfield
    starBartBrothers:
        number: L81
        tags: Playfield
    shootAgain:
        number: L82
        tags: Playfield
    starShowdown:
        number: L83
        tags: Playfield
    badGuyL1:
        number: L84
        tags: Playfield
    startButton:
        number: L88
        tags: Playfield
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05

PRBallSave:
    pulseCoils: [minePopper, saloonPopper, leftJetBumper, rightJetBumper, bottomJetBumper,moveBart, moveBartHat,moveBart]
    resetSwitches:
        shooterLane: open
        rightOutlane: open
        leftOutlane: open
        rightReturnLane: open
        leftReturnLane: open
        rightRampMake: open
        leftRampEnter: open
        centerRampMake: open
        leftLoopBottom: open
        rightLoopBottom: open
        mineEntrance: open
        saloonGate: open
        beerMug: open
    stopSwitches:
        shooterLane: closed
        minePopper: active
        saloonPopper: active
        # don't ball search if a flipper button is pressed
        flipperLwL: closed
        flipperLwR: closed

