##   ____           _                ____
##  / ___|__ _  ___| |_ _   _ ___   / ___|__ _ _ __  _   _  ___  _ __
## | |   / _` |/ __| __| | | / __| | |   / _` | '_ \| | | |/ _ \| '_ \
## | |__| (_| | (__| |_| |_| \__ \ | |__| (_| | | | | |_| | (_) | | | |
##  \____\__,_|\___|\__|\__,_|___/  \____\__,_|_| |_|\__, |\___/|_| |_|
##                                                   |___/
##           ___ ___  _  _ _____ ___ _  _ _   _ ___ ___
##          / __/ _ \| \| |_   _|_ _| \| | | | | __|   \
##         | (_| (_) | .` | | |  | || .` | |_| | _|| |) |
##          \___\___/|_|\_| |_| |___|_|\_|\___/|___|___/
##
## A P-ROC Project by Eric Priepke, Copyright 2012
## Built on the PyProcGame Framework from Adam Preble and Gerry Stellenberg
## Original Cactus Canyon software by Matt Coriale
##

# P-ROC Game Description file for Bally Cactus Canyon
PRGame:
    machineType: wpc95
    numBalls: 4
PRFlippers:
    - flipperLwR
    - flipperLwL
PRBumpers:
    - leftSlingshot
    - rightSlingshot
    - leftJetBumper
    - rightJetBumper
    - bottomJetBumper
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #    'NC' (normally closed.  Common for optos)

    #Flipper Grounded Swithes
    ## EOS switches?
    flipperLwR:
        number: SF2
        label: Right Flipper
        tags: Grounded,0,2
    flipperLwL:
        number: SF4
        label: Left Flipper
        tags: Grounded,0,4

    #Dedicated Grounded Swtches
    leftCoin:
        number: SD1
        label: Left Coin Chute
        tags: Dedicated,0,1
    centerCoin:
        number: SD2
        label: Center Coin Chute
        tags: Dedicated,0,2
    rightCoin:
        number: SD3
        label: Right Coin Chute
        tags: Dedicated,0,3
    fourthCoin:
        number: SD4
        label: 4th Coin Chute
        tags: Dedicated,0,4
    exit: 
        number: SD5
        label: Exit
        tags: Dedicated,0,5
    down: 
        number: SD6
        label: Down
        tags: Dedicated,0,6
    up: 
        number: SD7
        label: Up
        tags: Dedicated,0,7
    enter: 
        number: SD8
        label: Enter
        tags: Dedicated,0,8

    #Regular Switches
    phantomSwitch2:
        number: S11
    phantomSwitch3:
        number: S12
    startButton:
        number: S13
        label: Start Button
        tags: Standard,1,3
    plumbBobTilt:
        number: S14
        label: Tilt Plumb Bob
        tags: Standard,1,4
    mineEntrance:
        number: S15
        label: Mine Entrance
        tags: Standard,1,5
    leftOutlane:
        number: S16
        label: Left Outlane
        tags: Standard,1,6
    rightReturnLane:
        number: S17
        label: Right Return Lane
        tags: Standard,1,7
    shooterLane:
        number: S18
        label: Shooter Lane
        tags: Standard,1,8
    tilt:
        number: S21
        label: Tilt Plumb
        tags: Standard,2,1
    coinDoorClosed:
        number: S22
        label: Coin Door Closed
        tags: Standard,2,2
    alwaysClosed:
        number: S24
        label: Always Closed
        tags: Standard,2,4
    leftReturnLane:
        number: S26
        label: Left Return Lane
        tags: Standard,2,6
    rightOutlane:
        number: S27
        label: Right Outlane
        tags: Standard,2,7
    bottomRightStandUp:
        number: S28
        label: Bottom Right QD Target
        tags: Standard,2,8
    troughEject:
        number: S31
        label: Trough Eject Sensor
        tags: Standard,3,1
        type: 'NC'
    troughBallOne:
        number: S32
        label: Trough Ball 1
        tags: Standard,3,2
        type: 'NC'
    troughBallTwo:
        number: S33
        label: Trough Ball 2
        tags: Standard,3,3
        type: 'NC'
    troughBallThree:
        number: S34
        label: Trough Ball 3
        tags: Standard,3,4
        type: 'NC'
    troughBallFour:
        number: S35
        label: Trough Ball 4
        tags: Standard,3,5
        type: 'NC'
    leftLoopBottom:
        number: S36
        label: Left Loop Bottom
        tags: Standard,3,6
        type: 'NC'
    rightLoopBottom:
        number: S37
        label: Right Loop Bottom
        tags: Standard,3,7
        type: 'NC'
    minePopper:
        number: S41
        label: Mine Popper
        tags: Standard,4,1
        type: 'NC'
    saloonPopper:
        number: S42
        label: Saloon Popper
        tags: Standard,4,2
        type: 'NC'
    phantomSwitch:
        number: S43
    topRightStandUp:
        number: S44
        label: Top Right QD Target
        tags: Standard,4,4
    phantomSwitch4:
        number: S45
    beerMug:
        number: S46
        label: Beer Mug
        tags: Standard,4,6
    leftBonusLane:
        number: S47
        label: Left Bonus Lane
        tags: Standard,4,7
    jetBumpersExit:
        number: S48
        label: Jet Bumpers Exit
        tags: Standard,4,8
    leftSlingshot:
        number: S51
        label: Left Slingshot
        tags: Standard,5,1
    rightSlingshot:
        number: S52
        label: Right Slingshot
        tags: Standard,5,2
    leftJetBumper:
        number: S53
        label: Left Jet Bumper
        tags: Standard,5,3
    rightJetBumper:
        number: S54
        label: Right Jet Bumper
        tags: Standard,5,4
    bottomJetBumper:
        number: S55
        label: Bottom Jet Bumper
        tags: Standard,5,5
    rightLoopTop:
        number: S56
        label: Right Loop Top
        tags: Standard,5,6
    rightBonusLane:
        number: S57
        label: Right Bonus Lane
        tags: Standard,5,7
    leftLoopTop:
        number: S58
        label: Left Loop Top
        tags: Standard,5,8
    badGuySW0:
        number: S61
        label: Left Drop Target
        tags: Standard,6,1
    badGuySW1:
        number: S62
        label: Left CTR Drop Target
        tags: Standard,6,2
    badGuySW2:
        number: S63
        label: Right CTR Drop Target
        tags: Standard,6,3
    badGuySW3:
        number: S64
        label: Right Drop Target
        tags: Standard,6,4
    rightRampMake:
        number: S65
        label: Right Ramp Make
        tags: Standard,6,5
    rightRampEnter:
        number: S66
        label: Right Ramp Enter
        tags: Standard,6,6
    skillBowl:
        number: S67
        lable: Skill Bowl
        tags: Standard,6,7
    rightRampBottom:
        number: S68
        label: Right Ramp Bottom
        tags: Standard,6,8
    trainEncoder:
        number: S71
        label: Train Encoder
        tags: Standard,7,1
    trainHome:
        number: S72
        label: Train Home
        tags: Standard,7,2
    saloonGate:
        number: S73
        label: Saloon Gate
        tags: Standard,7,3
    saloonBart:
        number: S75
        label: Bart Brother Toy
        tags: Standard,7,5
    mineHome:
        number: S77
        label: Mine Home
        tags: Standard,7,7
        type: 'NC'
    mineEncoder:
        number: S78
        label: Mine Encoder
        tags: Standard,7,8
        type: 'NC'
    centerRampEnter:
        number: S82
        label: Center Ramp Enter
        tags: Standard,8,2
    leftRampMake:
        number: S83
        label: Left Ramp Make
        tags: Standard,8,3
    centerRampMake:
        number: S84
        label: Center Ramp Make
        tags: Standard,8,4
    leftRampEnter:
        number: S85
        label: Left Ramp Enter
        tags: Standard,8,5
    topLeftStandUp:
        number: S86
        label: Top Left QD Target
        tags: Standard,8,6
    bottomLeftStandUp:
        number: S87
        label: Bottom Left QD Target
        tags: Standard,8,7
    
PRCoils:
    flipperLwRMain:
        number: FLRM
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
    flipperLwLHold:
        number: FLLH
    moveBart:
        number: FURM
    moveBartHat:
        number: FULH
    autoPlunger:
        number: C01
    badGuyC0:
        number: C02
    badGuyC1:
        number: C03
    badGuyC2:
        number: C04
    badGuyC3:
        number: C05
    minePopper:
        number: C06
    knocker:
        number: C07
    saloonPopper:
        number: C08
    troughEject:
        number: C09
    leftSlingshot:
        number: C10
    rightSlingshot:
        number: C11
    leftJetBumper:
        number: C12
    rightJetBumper:
        number: C13
    leftGunFightPost:
        number: C14
    rightGunFightPost:
        number: C15
    bottomJetBumper:
        number: C16
    mineMotor:
        number: C17
    mineFlasher:
        number: C18
    leftGunFlasher:
        number: C19
    rightGunFlasher:
        number: C20
    leftLoopGate:
        number: C21
    rightLoopGate:
        number: C22
    beaconFlasher:
        number: C24
    middleRightFlasher:
        number: C25
    saloonFlasher:
        number: C26
    backRightFlasher:
        number: C27
    backLeftFlasher:
        number: C28
    trainReverse:
        number: C37
    trainForward:
        number: C38

PRLamps:
    rankStranger:
        number: L11
        tags: Playfield,Main
    rankPartner:
        number: L12
        tags: Playfield,Main
    rankDeputy:
        number: L13
        tags: Playfield,Main
    rankSheriff:
        number: L14
        tags: Playfield,Main
    rankMarshall:
        number: L15
        tags: Playfield,Main
    starMotherlode:
        number: L16
        tags: Playfield,Badge
    leftBonusLane:
        number: L17
        tags: Playfield
    rightBonusLane:
        number: L18
        tags: Playfield
    bountyBeacon:
        number: L21
        tags: Playfield,Main
    jackpotBeacon:
        number: L22
        tags: Playfield,Main
    shootToCollect:
        number: L23
        tags: Playfield,Main
    extraBallLitBeacon:
        number: L24
        tags: Playfield,Main
    bountySaloon:
        number: L25
        tags: Playfield,Main
    saloonArrow:
        number: L26
        tags: Playfield,Main
    extraBall:
        number: L27
        tags: Playfield,Main
    mineLock:
        number: L28
        tags: Playfield,Main
    badGuyL2:
        number: L31
        tags: Playfield
    badGuyL0:
        number: L32
        tags: Playfield
    leftQuickdraw:
        number: L33
        tags: Playfield,Main
    rightRampSoundAlarm:
        number: L34
        tags: Playfield,Main,rightRamp
    rightRampShootOut:
        number: L35
        tags: Playfield,Main,rightRamp
    rightRampSavePolly:
        number: L36
        tags: Playfield,Main,rightRamp
    rightRampJackpot:
        number: L37
        tags: Playfield,Main,rightRamp
    rightRampCombo:
        number: L38
        tags: Playfield,rightRamp
    rightLoopCombo:
        number: L41
        tags: Playfield,rightLoop
    rightLoopJackpot:
        number: L42
        tags: Playfield,Main,rightLoop
    rightLoopMarksman:
        number: L43
        tags: Playfield,Main,rightLoop
    rightLoopGunslinger:
        number: L44
        tags: Playfield,Main,rightLoop
    rightLoopGoodShot:
        number: L45
        tags: Playfield,Main,rightLoop
    leftReturnQuickdraw:
        number: L46
        tags: Playfield,Main
    leftGunfightPin:
        number: L47
        tags: Playfield,Main
    leftOutGunfight:
        number: L48
        tags: Playfield,Main
    badGuyL3:
        number: L51
        tags: Playfield
    bottomRightQuickdraw:
        number: L52
        tags: Playfield,Main
    topRightQuickdraw:
        number: L53
        tags: Playfield,Main
    centerRampCatchTrain:
        number: L54
        tags: Playfield,Main,centerRamp
    centerRampStopTrain:
        number: L55
        tags: Playfield,Main,centerRamp
    centerRampSavePolly:
        number: L56
        tags: Playfield,Main,centerRamp
    centerRampJackpot:
        number: L57
        tags: Playfield,Main,centerRamp
    centerRampCombo:
        number: L58
        tags: Playfield,centerRamp
    leftRampWhiteWater:
        number: L61
        tags: Playfield,Main,leftRamp
    leftRampWaterfall:
        number: L62
        tags: Playfield,Main,leftRamp
    leftRampSavePolly:
        number: L63
        tags: Playfield,Main,leftRamp
    leftRampJackpot:
        number: L64
        tags: Playfield,Main,leftRamp
    leftRampCombo:
        number: L65
        tags: Playfield,leftRamp
    rightReturnQuickdraw:
        number: L66
        tags: Playfield,Main
    rightOutSpecial:
        number: L67
        tags: Playfield,Main
    rightGunfightPin:
        number: L68
        tags: Playfield,Main
    starStampede:
        number: L71
        tags: Playfield,Badge
    starCombo:
        number: L72
        tags: Playfield,Badge
    starHighNoon:
        number: L73
        tags: Playfield,Badge
    leftLoopCombo:
        number: L74
        tags: Playfield,leftLoop
    leftLoopJackpot:
        number: L75
        tags: Playfield,Main,leftLoop
    leftLoopRideEm:
        number: L76
        tags: Playfield,Main,leftLoop
    leftLoopWildRide:
        number: L77
        tags: Playfield,Main,leftLoop
    leftLoopBuckNBronco:
        number: L78
        tags: Playfield,Main,leftLoop
    starBartBrothers:
        number: L81
        tags: Playfield,Badge
    shootAgain:
        number: L82
        tags: Playfield,Main
    starShowdown:
        number: L83
        tags: Playfield,Badge
    badGuyL1:
        number: L84
        tags: Playfield
    beerMug:
        number: L85
        tags: Playfield
    startButton:
        number: L88
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05

PRBallSave:
    pulseCoils: [minePopper, saloonPopper, leftJetBumper, rightJetBumper, bottomJetBumper,moveBart, moveBartHat,moveBart]
    resetSwitches:
        rightOutlane: open
        leftOutlane: open
        rightReturnLane: open
        leftReturnLane: open
        rightRampEnter: open
        leftRampEnter: open
        centerRampEnter: open
        leftLoopBottom: open
        rightLoopBottom: open
        mineEntrance: open
        saloonGate: open
        beerMug: open
        leftJetBumper: open
    stopSwitches:
        shooterLane: closed
        minePopper: active
        saloonPopper: active
        # don't ball search if a flipper button is pressed
        flipperLwL: closed
        flipperLwR: closed

