##   ____           _                ____
##  / ___|__ _  ___| |_ _   _ ___   / ___|__ _ _ __  _   _  ___  _ __
## | |   / _` |/ __| __| | | / __| | |   / _` | '_ \| | | |/ _ \| '_ \
## | |__| (_| | (__| |_| |_| \__ \ | |__| (_| | | | | |_| | (_) | | | |
##  \____\__,_|\___|\__|\__,_|___/  \____\__,_|_| |_|\__, |\___/|_| |_|
##                                                   |___/
##           ___ ___  _  _ _____ ___ _  _ _   _ ___ ___
##          / __/ _ \| \| |_   _|_ _| \| | | | | __|   \
##         | (_| (_) | .` | | |  | || .` | |_| | _|| |) |
##          \___\___/|_|\_| |_| |___|_|\_|\___/|___|___/
##
## A P-ROC Project by Eric Priepke, Copyright 2012
## Built on the PyProcGame Framework from Adam Preble and Gerry Stellenberg
## Original Cactus Canyon software by Matt Coriale
##
# This file is a template for all of the settings used in the game.  The game code will
# load this file along with a user_settings.yaml file.  Any settings not present in
# the user_settings.yaml file will default to the default value specified here.  When
# any setting is saved (via the in-game service menu), the user_settings.yaml file
# will be updated with ALL of the entries here without overwriting existing settings.

Machine (Standard):
  'Balls Per Game':
    options: [1,10]
    increments: 1
    default: 3
  'Tilt Warnings':
    options: [1,10]
    increments: 1
    default: 2
  'Maximum Extra Balls':
    options: [0,10]
    increments: 1
    default: 2
  'Game Restart':
    options: [True,False]
    default: True
  'Flipper Pulse':
    options: [25,40]
    increments: 1
    default: 30
  'Drop Target Boost':
    options: [0,30]
    increments: 5
    default: 0
  'Mine Kicker Strength':
    options: [20,50]
    increments: 5
    default: 20
  'Autoplunger Strength':
    options: [20,50]
    increments: 5
    default: 20
  'Trough Strength':
    options: [20,50]
    increments: 5
    default: 30
Sound:
  'Initial volume':
    options: [1,2,3,4,5,6,7,8,9,10]
    default: 5
  'Music volume offset':
    options: [-0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4]
    default: 0
Display:
  'Left side score justify':
    # This example has no default.  The first option (right) will be used as the default.
    options: [right, left]
Replay:
  'Replay Type':
    options: ['none','auto','fixed','incremental']
    default: 'auto'
  'Replay Percentage':
    options: [5,40]
    increments: 5
    default: 10
  'Replay Award':
    options: ['Audit', 'Extra Ball']
    default: 'Audit'
  'Replay Levels':
    options: [1,2,3,4]
    default: 1
  'Replay Level 1':
    options: [50000,5000000]
    increments: 50000
    default: 100000
  'Replay Level 2':
    options: [100000,5000000]
    increments: 50000
    default: 200000
  'Replay Level 3':
    options: [150000,5000000]
    increments: 50000
    default: 300000
  'Replay Level 4':
    options: [200000,5000000]
    increments: 50000
    default: 400000
  'Replay Boost':
    options: [50000,5000000]
    increments: 50000
    default: 100000
  'Special':
    options: ['Audit', 'Extra Ball','Points']
    default: 'Audit'
Highscore:
  'Grand Champion':
    options: [50000000,500000000]
    increments: 50000000
    default: 350000000
Gameplay (Feature):
  'Attract sounds to play':
    options: [3,10]
    increments: 1
    default: 3
  'Attract sound delay time':
    options: [30,600]
    increments: 10
    default: 120
  'Combo Timer':
    options: [3,10]
    increments: 1
    default: 7
  'Combos for Star':
    options: [5,20]
    increments: 1
    default: 10
  'Beer Mug Hits For Multiball':
    options: [2,20]
    increments: 1
    default: 5
  'Bart Brothers Difficulty':
    options: ['Easy','Hard']
    default: 'Easy'
  'Bart Brothers for Star':
    options: [2,10]
    increments: 1
    default: 3
  'Quickdraw Timer':
    options: [5,30]
    increments: 5
    default: 20
  'Ambush Target Timer':
    options: [5,30]
    increments: 1
    default: 12
  'Ambush Escapes to Lose':
    options: [3,15]
    increments: 1
    default: 3
  'Ambush Awards Badge':
    options: ['Yes','No']
    default: 'No'
  'Ambush or Showdown First':
    options: ['Ambush','Showdown']
    default: 'Showdown'
  'Save Polly Shots - Train':
    options: [2,15]
    increments: 1
    default: 5
  'Save Polly Shots - River':
    options: [2,15]
    increments: 1
    default: 3
  'Save Polly Timer - River':
    options: [15,60]
    increments: 5
    default: 30
  'Save Polly Timer - Bank':
    options: [15,60]
    increments: 5
    default: 30
  'Save Polly Wins Required':
    options: ['Yes','No']
    default: 'No'
  'Shots to defeat Bionic Bart':
    options: [2,10]
    increments: 1
    default: 3
  'Bionic Bart Ball Save':
    options: ['Enabled','Disabled']
    default: 'Disabled'
  'Bionic Bart Ball Save Timer':
    options: [5,40]
    increments: 5
    default: 15
  'Move Your Train Mode':
    options: ['Enabled','Disabled']
    default: 'Enabled'
  'Drunk Multiball Stacking':
    options: ['Enabled','Disabled']
    default: 'Enabled'
  'Marshall Multiball':
    options: ['Enabled','Disabled']
    default: 'Enabled'
  'Marshall Jackpot Timer':
    options: [5,60]
    increments: 5
    default: 15
  'Marshall Multiball Music':
    options: ['Yes','No']
    default: 'No'
  'Quickdraws Lit Difficulty':
    options: ['Easy','Hard']
    default: 'Easy'
  'Multiball Locks Difficulty':
    options: ['Easy','Hard']
    default: 'Easy'
  'Showdown Difficulty':
    options: ['Easy','Hard']
    default: 'Easy'
  'Motherlode Badge Difficulty':
    options: ['Easy','Normal']
    default: 'Normal'
  'Gold Mine Multiball Restart':
    options: ['Yes','No']
    default: 'Yes'
  'Gold Mine Restart Timer':
    options: [5,15]
    increments: 1
    default: 8
  'Marshall Required for Bionic':
    options: ['Yes','No']
    default: 'No'
  'Multiball Ball Savers':
    options: ['Yes','No']
    default: 'No'
  'Multiball Savers Timer':
    options: [5,30]
    increments: 5
    default: 10
  'Skillshot Boosts':
    options: ['Easy','Hard']
    default: 'Easy'
  'Polly Dies Animation':
    options: ['Show','Hide']
    default: 'Show'
  'Drunk Multiball Intro Skip':
    options: ['Yes','No']
    default: 'No'
  'Tumbleweeds for CVA':
    options: [2,20]
    increments: 1
    default: 3
  'Attract Mode Sounds':
    options: ['Yes','No']
    default: 'Yes'
  'Attract Mode Music':
    options: ['Yes','No']
    default: 'Yes'